[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "speedtest-cli-ng"
description = "Next generation CLI for testing internet bandwidth using speedtest.net"
keywords = ["speedtest", "speedtest.net", "bandwidth", "internet", "cli"]
license = "Apache-2.0"
version = "0.3.0"
requires-python = ">=3.14"
authors = [{ name = "Michał Korczak", email = "git@omikor.in" }]
license-files = ["LICENSE", "NOTICE"]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: System :: Networking",
    "Topic :: Terminals",
    "Topic :: Utilities",
]
dependencies = [
    "httpx2>=2.12.0,<3",
    "rich>=15.0.0,<16",
]

[project.urls]
Homepage = "https://github.com/Omikorin/speedtest-cli"
Source = "https://github.com/Omikorin/speedtest-cli"
Issues = "https://github.com/Omikorin/speedtest-cli/issues"

[project.scripts]
speedtest = "speedtest.__main__:main"
speedtest-cli = "speedtest.__main__:main"
speedtest-cli-ng = "speedtest.__main__:main"

[dependency-groups]
dev = [
    # Tests
    "pytest>=9.1.1,<10",
    "pytest-cov>=7.1.0,<8",
    # Linting
    "ruff>=0.16.4,<1",
    "ty>=0.0.73,<1",
]

[tool.hatch.build.targets.sdist]
exclude = [
    ".github",
    ".python-version",
    "renovate.json5",
]

[tool.hatch.build.targets.wheel]
packages = ["src/speedtest"]

[tool.uv]
required-version = ">=0.12.0"
exclude-newer = "7 days"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.ruff]
line-length = 120
src = ["speedtest", "tests"]

[tool.ruff.lint]
extend-select = [
    "ANN", # flake8 annotations
    "B",   # flake8 bugbear
    "PYI", # flake8 pyi
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8 naming
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
]
preview = true
ignore = []
unfixable = ["B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ty.rules]
missing-type-argument = "error"
possibly-unresolved-reference = "warn"

[tool.pytest]
minversion = "9.0"
# Automatically show extra test info, fail if coverage drops, and output a terminal coverage report
addopts = ["-v", "--cov=speedtest", "--cov-report=term-missing"]
testpaths = ["tests"]
