[wheel]
universal=1

[metadata]
name = speedtest-cli-ng
version = attr: speedtest.__version__
author = Michał Korczak
author_email = git@omikor.in
url = https://github.com/Omikorin/speedtest-cli-ng
license = Apache License, Version 2.0
description = Command line interface for testing internet bandwidth using speedtest.net
long_description = file: README.md
long_description_content_type = text/markdown
keywords = speedtest, speedtest.net, bandwidth, internet, cli
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python
    Programming Language :: Python :: 3 :: Only
    Environment :: Console
    Intended Audience :: Developers
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Topic :: Internet :: WWW/HTTP
    Topic :: System :: Networking
    Topic :: Terminals
    Topic :: Utilities
project_urls =
    GitHub = https://github.com/Omikorin/speedtest-cli-ng

[options]
packages = find:
python_requires = >=3.12

[options.packages.find]
include =
    speedtest
    speedtest.*

[options.entry_points]
console_scripts =
    speedtest = speedtest.__main__:main
    speedtest-cli = speedtest.__main__:main

[options.data_files]
share/man/man1 =
    extras/man/speedtest-cli.1