.TH "speedtest-cli" 1 "2026-06-14" "speedtest-cli"
.SH NAME
speedtest\-cli \- Next generation CLI for testing internet bandwidth using speedtest.net
.SH SYNOPSIS
.B speedtest\-cli
[OPTION...]
.SH DESCRIPTION
Speedtest.net is a web service for testing your broadband connection by downloading a file
from a nearby speedtest.net server on the web. This tool allows you to access the service
from the command line.

.SH OPTIONS
Usage: speedtest\-cli [OPTION...]

.B Help Options

\fB\-h, \-\-help\fR
.RS
Displays usage for the tool.
.RE

.B Core Options

\fB\-l, \-\-list\fR
.RS
Show available speedtest.net servers sorted by distance.
.RE

\fB\-s, \-\-server SERVER\fR
.RS
Specify a server id to test against.
.RE

.B Transfer Modifiers

\fB\-\-no\-download\fR
.RS
Do not perform the download test.
.RE

\fB\-\-no\-upload\fR
.RS
Do not perform the upload test.
.RE

\fB\-t, \-\-threads THREADS\fR
.RS
Set the number of concurrent connections instead of using downloaded config.
.RE

\fB\-\-single\fR
.RS
Use one concurrent connection. Simulates a typical file transfer.
.RE

.B Output Options

\fB\-\-share\fR
.RS
Generate and provide a URL to the speedtest.net share results image.
.RE

\fB\-\-bytes\fR
.RS
Display values in bytes instead of bits. Does not affect image generation or JSON/CSV output.
.RE

\fB\-\-csv\fR
.RS
Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s.
.RE

\fB\-\-json\fR
.RS
Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s.
.RE

\fB\-\-csv\-delimiter CSV_DELIMITER\fR
.RS
Single character delimiter to use in CSV output. Default ","
.RE

\fB\-\-csv\-header\fR
.RS
Print CSV headers and exit.
.RE

.B Connection Options

\fB\-\-source SOURCE\fR
.RS
Bind a source IP address to use for connections.
.RE

\fB\-\-timeout TIMEOUT\fR
.RS
HTTP timeout in seconds. Default 10.0
.RE

\fB\-\-debug\fR
.RS
Show verbose debugging output.
.RE

\fB\-\-version\fR
.RS
Show the version number and exit.
.RE

.SH EXAMPLES

\fBAutomatically find closest server and start testing\fR
.RS
speedtest\-cli
.RE

\fBSpecify testing against server 1491\fR
.RS
speedtest-cli \-s 1491
.RE

.SH REPORTING BUGS
Please file issues on the GitHub bug tracker: https://github.com/Omikorin/speedtest\-cli

.SH AUTHORS
This manual page was originally written by Jonathan Carter <jonathan@ubuntu.com>
speedtest\-cli was originally written by Matt Martz <matt@sivel.net>
Forked and maintained by Michał Korczak <git@omikor.in>.
