"""
Command line interface parser.
"""

import argparse
import errno
import signal
import threading
from http.client import HTTPSConnection
from typing import Any, Callable

from speedtest import __version__
from speedtest.exceptions import (
    ConfigRetrievalError,
    InvalidServerIDType,
    NoMatchedServers,
    ServersRetrievalError,
    SpeedtestCLIError,
)
from speedtest.http import HTTP_ERRORS
from speedtest.results import SpeedtestResults
from speedtest.speedtest import Speedtest
from speedtest.status import ExitStatus
from speedtest.utils import do_nothing, print_dots, printer


def ctrl_c(shutdown_event: threading.Event) -> Callable[[int, Any], None]:
    """Catch Ctrl-C key sequence and set a SHUTDOWN_EVENT for our threaded operations."""

    def inner(signum: int, frame: Any) -> None:
        shutdown_event.set()
        print("Stopping speedtest-cli...")
        raise KeyboardInterrupt

    return inner


def version() -> int:
    """Print the version."""

    print(f"speedtest-cli-ng {__version__}")
    return ExitStatus.SUCCESS


def csv_header(delimiter: str = ",") -> int:
    """Print the CSV Headers."""

    print(SpeedtestResults.csv_header(delimiter=delimiter))
    return ExitStatus.SUCCESS


def parse_args() -> argparse.Namespace:
    """Function to handle building and parsing of command line arguments."""

    description = (
        "Command line interface for testing internet bandwidth using speedtest.net.\n"
        "--------------------------------------------------------------------------\n"
        "https://github.com/Omikorin/speedtest-cli-ng"
    )

    parser = argparse.ArgumentParser(description=description)

    parser.add_argument(
        "--single",
        default=False,
        action="store_true",
        help="Only use a single connection instead of multiple. This simulates a typical file transfer.",
    )
    parser.add_argument(
        "--no-download",
        dest="download",
        default=True,
        action="store_const",
        const=False,
        help="Do not perform download test",
    )
    parser.add_argument(
        "--no-upload",
        dest="upload",
        default=True,
        action="store_const",
        const=False,
        help="Do not perform upload test",
    )
    parser.add_argument(
        "--bytes",
        dest="units",
        action="store_const",
        const=("byte", 8),
        default=("bit", 1),
        help="Display values in bytes instead of bits. Does not affect the image generated by --share, nor output from --json or --csv",
    )
    parser.add_argument(
        "--share",
        action="store_true",
        help="Generate and provide a URL to the speedtest.net share results image, not displayed with --csv",
    )
    parser.add_argument(
        "--simple",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic information",
    )
    parser.add_argument(
        "--csv",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s and not affected by --bytes",
    )
    parser.add_argument(
        "--csv-delimiter",
        default=",",
        type=str,
        help='Single character delimiter to use in CSV output. Default ","',
    )
    parser.add_argument(
        "--csv-header", action="store_true", default=False, help="Print CSV headers"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s and not affected by --bytes",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Display a list of speedtest.net servers sorted by distance",
    )
    parser.add_argument(
        "--server",
        type=int,
        action="append",
        help="Specify a server ID to test against. Can be supplied multiple times",
    )
    parser.add_argument("--source", help="Source IP address to bind to")
    parser.add_argument(
        "--timeout", default=10, type=float, help="HTTP timeout in seconds. Default 10"
    )
    parser.add_argument(
        "--secure",
        action="store_true",
        help="Use HTTPS instead of HTTP when communicating with speedtest.net operated servers",
    )
    parser.add_argument(
        "--no-pre-allocate",
        dest="pre_allocate",
        action="store_const",
        default=True,
        const=False,
        help="Do not pre allocate upload data. Pre allocation is enabled by default to improve upload performance. To support systems with insufficient memory, use this option to avoid a MemoryError",
    )
    parser.add_argument(
        "--version", action="store_true", help="Show the program version"
    )
    parser.add_argument(
        "--debug", action="store_true", default=False, help="Show debugging output"
    )

    return parser.parse_args()


def validate_optional_args(args: argparse.Namespace) -> None:
    """Check if an argument was provided that depends on a module that may
    not be part of the Python standard library.
    """

    # We only check if HTTPSConnection is available (it may be disabled if Python was compiled without SSL).
    optional_args = {
        "secure": ("SSL support", HTTPSConnection),
    }

    for arg, info in optional_args.items():
        if getattr(args, arg, False) and info[1] is None:
            raise SystemExit(f"{info[0]} is not installed. --{arg} is unavailable")


def shell() -> int:
    """Run the full speedtest.net test."""

    shutdown_event = threading.Event()
    signal.signal(signal.SIGINT, ctrl_c(shutdown_event))

    args = parse_args()

    if args.version:
        return version()

    if not args.download and not args.upload:
        raise SpeedtestCLIError("Cannot supply both --no-download and --no-upload")

    if len(args.csv_delimiter) != 1:
        raise SpeedtestCLIError("--csv-delimiter must be a single character")

    if args.csv_header:
        return csv_header(args.csv_delimiter)

    validate_optional_args(args)

    quiet = bool(args.simple or args.csv or args.json)
    machine_format = bool(args.csv or args.json)

    callback = do_nothing if (quiet or args.debug) else print_dots(shutdown_event)

    printer("Retrieving speedtest.net configuration...", quiet)

    try:
        st = Speedtest(
            source_address=args.source, timeout=args.timeout, secure=args.secure
        )
    except (*HTTP_ERRORS, ConfigRetrievalError) as e:
        printer("Cannot retrieve speedtest configuration", error=True)
        raise SpeedtestCLIError(e) from e

    if args.list:
        try:
            st.get_servers()
        except (*HTTP_ERRORS, ServersRetrievalError) as e:
            printer("Cannot retrieve speedtest server list", error=True)
            raise SpeedtestCLIError(e) from e

        for _, servers in sorted(st.servers.items()):
            for server in servers:
                line = f"{server['id']:>5}) {server['sponsor']} ({server['name']}, {server['country']}) [{server['d']:.2f} km]"
                try:
                    printer(line)
                except IOError as e:
                    if e.errno != errno.EPIPE:
                        raise
        return ExitStatus.SUCCESS

    printer(
        f"Testing from {st.config['client']['isp']} ({st.config['client']['ip']})...",
        quiet,
    )

    printer("Retrieving speedtest.net server list...", quiet)
    try:
        st.get_servers(servers=args.server)
    except NoMatchedServers:
        servers_list = ", ".join(str(s) for s in args.server)
        raise SpeedtestCLIError(f"No matched servers: {servers_list}")
    except (*HTTP_ERRORS, ServersRetrievalError) as e:
        printer("Cannot retrieve speedtest server list", error=True)
        raise SpeedtestCLIError(e) from e
    except InvalidServerIDType:
        servers_list = ", ".join(str(s) for s in args.server)
        raise SpeedtestCLIError(
            f"{servers_list} is an invalid server type, must be an int"
        )

    if args.server and len(args.server) == 1:
        printer("Retrieving information for the selected server...", quiet)
    else:
        printer("Selecting best server based on ping...", quiet)

    st.get_best_server()
    results = st.results

    printer(
        f"Hosted by {results.server['sponsor']} ({results.server['name']}) "
        f"[{results.server['d']:.2f} km]: {results.server['latency_ms']:.4f} ms",
        quiet,
    )

    if args.download:
        printer("Testing download speed", quiet, end="\n" if args.debug else "")
        st.download(callback=callback, threads=1 if args.single else None)
        download_speed = (results.download / 1_000_000) / args.units[1]
        printer(f"Download: {download_speed:.2f} M{args.units[0]}/s", quiet)
    else:
        printer("Skipping download test", quiet)

    if args.upload:
        printer("Testing upload speed", quiet, end="\n" if args.debug else "")
        st.upload(
            callback=callback,
            pre_allocate=args.pre_allocate,
            threads=1 if args.single else None,
        )
        upload_speed = (results.upload / 1_000_000) / args.units[1]
        printer(f"Upload: {upload_speed:.2f} M{args.units[0]}/s", quiet)
    else:
        printer("Skipping upload test", quiet)

    printer(f"Results:\n{results.dict()!r}", debug=True)

    if not args.simple and args.share:
        results.share()

    if args.simple:
        download_speed = (results.download / 1_000_000) / args.units[1]
        upload_speed = (results.upload / 1_000_000) / args.units[1]
        printer(
            f"Ping: {results.ping:.4f} ms\n"
            f"Download: {download_speed:.2f} M{args.units[0]}/s\n"
            f"Upload: {upload_speed:.2f} M{args.units[0]}/s"
        )
    elif args.csv:
        printer(results.csv(delimiter=args.csv_delimiter))
    elif args.json:
        printer(results.json())

    if args.share and not machine_format:
        printer(f"Share results: {results.share()}")

    return ExitStatus.SUCCESS
