"""
Command line interface parser.

"""

from argparse import ArgumentParser
import errno
import signal
import sys
import threading

try:
    from http.client import HTTPSConnection
except ImportError:
    HTTPSConnection = None


from speedtest import __version__
from speedtest.exceptions import (
    ConfigRetrievalError,
    InvalidServerIDType,
    NoMatchedServers,
    ServersRetrievalError,
    SpeedtestCLIError,
)
from speedtest.http import HTTP_ERRORS
from speedtest.results import SpeedtestResults
from speedtest.speedtest import Speedtest
from speedtest.status import ExitStatus
from speedtest.utils import DEBUG, do_nothing, print_dots, printer


def ctrl_c(shutdown_event):
    """Catch Ctrl-C key sequence and set a SHUTDOWN_EVENT for our threaded
    operations
    """

    def inner(signum, frame):
        shutdown_event.set()
        print("Cancelling...", file=sys.stderr)
        raise KeyboardInterrupt

    return inner


def version():
    """Print the version"""

    print("speedtest-cli-ng %s" % __version__)
    return ExitStatus.SUCCESS


def csv_header(delimiter=","):
    """Print the CSV Headers"""

    print(SpeedtestResults.csv_header(delimiter=delimiter))
    return ExitStatus.SUCCESS


def parse_args():
    """Function to handle building and parsing of command line arguments"""

    description = (
        "Command line interface for testing internet bandwidth using "
        "speedtest.net.\n"
        "------------------------------------------------------------"
        "--------------\n"
        "https://github.com/Omikorin/speedtest-cli-ng"
    )

    parser = ArgumentParser(description=description)

    parser.add_argument(
        "--single",
        default=False,
        action="store_true",
        help="Only use a single connection instead of "
        "multiple. This simulates a typical file "
        "transfer.",
    )
    parser.add_argument(
        "--no-download",
        dest="download",
        default=True,
        action="store_const",
        const=False,
        help="Do not perform download test",
    )
    parser.add_argument(
        "--no-upload",
        dest="upload",
        default=True,
        action="store_const",
        const=False,
        help="Do not perform upload test",
    )
    parser.add_argument(
        "--bytes",
        dest="units",
        action="store_const",
        const=("byte", 8),
        default=("bit", 1),
        help="Display values in bytes instead of bits. Does "
        "not affect the image generated by --share, nor "
        "output from --json or --csv",
    )
    parser.add_argument(
        "--share",
        action="store_true",
        help="Generate and provide a URL to the speedtest.net "
        "share results image, not displayed with --csv",
    )
    parser.add_argument(
        "--simple",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic " "information",
    )
    parser.add_argument(
        "--csv",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic "
        "information in CSV format. Speeds listed in "
        "bit/s and not affected by --bytes",
    )
    parser.add_argument(
        "--csv-delimiter",
        default=",",
        type=str,
        help="Single character delimiter to use in CSV " 'output. Default ","',
    )
    parser.add_argument(
        "--csv-header", action="store_true", default=False, help="Print CSV headers"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        default=False,
        help="Suppress verbose output, only show basic "
        "information in JSON format. Speeds listed in "
        "bit/s and not affected by --bytes",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Display a list of speedtest.net servers " "sorted by distance",
    )
    parser.add_argument(
        "--server",
        type=int,
        action="append",
        help="Specify a server ID to test against. Can be " "supplied multiple times",
    )
    parser.add_argument(
        "--exclude",
        type=int,
        action="append",
        help="Exclude a server from selection. Can be " "supplied multiple times",
    )
    parser.add_argument("--mini", help="URL of the Speedtest Mini server")
    parser.add_argument("--source", help="Source IP address to bind to")
    parser.add_argument(
        "--timeout", default=10, type=float, help="HTTP timeout in seconds. Default 10"
    )
    parser.add_argument(
        "--secure",
        action="store_true",
        help="Use HTTPS instead of HTTP when communicating "
        "with speedtest.net operated servers",
    )
    parser.add_argument(
        "--no-pre-allocate",
        dest="pre_allocate",
        action="store_const",
        default=True,
        const=False,
        help="Do not pre allocate upload data. Pre allocation "
        "is enabled by default to improve upload "
        "performance. To support systems with "
        "insufficient memory, use this option to avoid a "
        "MemoryError",
    )
    parser.add_argument(
        "--version", action="store_true", help="Show the program version"
    )
    parser.add_argument(
        "--debug", action="store_true", default=False, help="Show debugging output"
    )

    return parser.parse_args()


def validate_optional_args(args):
    """Check if an argument was provided that depends on a module that may
    not be part of the Python standard library.

    If such an argument is supplied, and the module does not exist, exit
    with an error stating which module is missing.
    """
    optional_args = {
        "secure": ("SSL support", HTTPSConnection),
    }

    for arg, info in optional_args.items():
        if getattr(args, arg, False) and info[1] is None:
            raise SystemExit(
                "%s is not installed. --%s is " "unavailable" % (info[0], arg)
            )


def shell():
    """Run the full speedtest.net test"""

    shutdown_event = threading.Event()

    signal.signal(signal.SIGINT, ctrl_c(shutdown_event))

    args = parse_args()

    if args.version:
        return version()

    if not args.download and not args.upload:
        raise SpeedtestCLIError("Cannot supply both --no-download and --no-upload")

    if len(args.csv_delimiter) != 1:
        raise SpeedtestCLIError("--csv-delimiter must be a single character")

    if args.csv_header:
        return csv_header(args.csv_delimiter)

    validate_optional_args(args)

    if args.debug:
        DEBUG = True

    if args.simple or args.csv or args.json:
        quiet = True
    else:
        quiet = False

    if args.csv or args.json:
        machine_format = True
    else:
        machine_format = False

    # Don't set a callback if we are running quietly
    if quiet or args.debug:
        callback = do_nothing
    else:
        callback = print_dots(shutdown_event)

    printer("Retrieving speedtest.net configuration...", quiet)
    try:
        speedtest = Speedtest(
            source_address=args.source, timeout=args.timeout, secure=args.secure
        )
    except (ConfigRetrievalError,) + HTTP_ERRORS as e:
        printer("Cannot retrieve speedtest configuration", error=True)
        raise SpeedtestCLIError(e) from e

    if args.list:
        try:
            speedtest.get_servers()
        except (ServersRetrievalError,) + HTTP_ERRORS as e:
            printer("Cannot retrieve speedtest server list", error=True)
            raise SpeedtestCLIError(e) from e

        for _, servers in sorted(speedtest.servers.items()):
            for server in servers:
                line = (
                    "%(id)5s) %(sponsor)s (%(name)s, %(country)s) "
                    "[%(d)0.2f km]" % server
                )
                try:
                    printer(line)
                except IOError as e:
                    if e.errno != errno.EPIPE:
                        raise
        return ExitStatus.SUCCESS

    printer("Testing from %(isp)s (%(ip)s)..." % speedtest.config["client"], quiet)

    if not args.mini:
        printer("Retrieving speedtest.net server list...", quiet)
        try:
            speedtest.get_servers(servers=args.server, exclude=args.exclude)
        except NoMatchedServers:
            raise SpeedtestCLIError(
                "No matched servers: %s" % ", ".join("%s" % s for s in args.server)
            )
        except (ServersRetrievalError,) + HTTP_ERRORS as e:
            printer("Cannot retrieve speedtest server list", error=True)
            raise SpeedtestCLIError(e) from e
        except InvalidServerIDType:
            raise SpeedtestCLIError(
                "%s is an invalid server type, must "
                "be an int" % ", ".join("%s" % s for s in args.server)
            )

        if args.server and len(args.server) == 1:
            printer("Retrieving information for the selected server...", quiet)
        else:
            printer("Selecting best server based on ping...", quiet)
        speedtest.get_best_server()
    elif args.mini:
        speedtest.get_best_server(speedtest.set_mini_server(args.mini))

    results = speedtest.results

    printer(
        "Hosted by %(sponsor)s (%(name)s) [%(d)0.2f km]: "
        "%(latency)s ms" % results.server,
        quiet,
    )

    if args.download:
        printer("Testing download speed", quiet, end=("", "\n")[bool(args.debug)])
        speedtest.download(callback=callback, threads=(None, 1)[args.single])
        printer(
            "Download: %0.2f M%s/s"
            % ((results.download / 1000.0 / 1000.0) / args.units[1], args.units[0]),
            quiet,
        )
    else:
        printer("Skipping download test", quiet)

    if args.upload:
        printer("Testing upload speed", quiet, end=("", "\n")[bool(args.debug)])
        speedtest.upload(
            callback=callback,
            pre_allocate=args.pre_allocate,
            threads=(None, 1)[args.single],
        )
        printer(
            "Upload: %0.2f M%s/s"
            % ((results.upload / 1000.0 / 1000.0) / args.units[1], args.units[0]),
            quiet,
        )
    else:
        printer("Skipping upload test", quiet)

    printer("Results:\n%r" % results.dict(), debug=True)

    if not args.simple and args.share:
        results.share()

    if args.simple:
        printer(
            "Ping: %s ms\nDownload: %0.2f M%s/s\nUpload: %0.2f M%s/s"
            % (
                results.ping,
                (results.download / 1000.0 / 1000.0) / args.units[1],
                args.units[0],
                (results.upload / 1000.0 / 1000.0) / args.units[1],
                args.units[0],
            )
        )
    elif args.csv:
        printer(results.csv(delimiter=args.csv_delimiter))
    elif args.json:
        printer(results.json())

    if args.share and not machine_format:
        printer("Share results: %s" % results.share())

    return ExitStatus.SUCCESS
